name = "arsen-portfolio-2025"
# Tell Cloudflare Pages where the static build artifacts are
pages_build_output_dir = "dist/arsen-portfolio-2025/browser"
  
# KV namespace binding
[[kv_namespaces]]
binding = "USERS"        # variable used in your code: env.USERS
id = "acb99670456648b9b5e97aadc7d83a72"  # your KV namespace ID

# Environment variables
[vars]
JWT_SECRET = "eb9gOdrAT54mGgcgu4W2rjqoj2mkMAmB"